SUBDIRS = tests
PROGRAMS = test.sh

include ../makefile.inc

clean: clean-default
clean-install: clean-install-default
build: build-default
test: test-default
lint: lint-default
install: install-default
